# ╭───────────────────────────ImplementationGuide-hl7.fhir.nz.base.json────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.org.nz.fhir.ig.cca
canonical: http://hl7.org.nz/fhir/ig/cca
version: 0.1.0
name: CcaImplementationGuide
title: HL7® FHIR® Te Aho o Te Kahu, Cancer Control Agency Implementation Guide
status: active
publisher:
  name: Te Aho o Te Kahu, Cancer Control Agency
description: CCA IG
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# use includes/menu.xml for pages as not all files will be present when sushi runs (extensions, profiles, terminology)

menu:
  IG Home: index.html
  Notes: notes.html
  API: CapabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Examples: examples.html
  Artifact Index: artifacts.html
  "Support\n      ":
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html
