
# ╭───────────────────────────ImplementationGuide-hl7.fhir.nz.base.json────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.nz.cca
canonical: http://hl7.org.nz/fhir/cca
version: 0.1.0
name: CcaImplementationGuide
title: HL7® FHIR® Te Aho o Te Kahu, Cancer Control Agency Implementation Guide
status: active
publisher:
  name: David Hay
  email: mailto:david.hay25@gmail.com
description: CCA IG
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# use includes/menu.xml as not all files will be present (extensions, profiles, terminology)
pagesX:
  index.md:
    title: Home
  examples.xml:
    title: Examples
  extensions.xml:
    title: Extensions
  notes.md:
    title: Notes
  profiles.xml:
    title: Profiles
  terminology.md:
    title: Terminology
  CapabilityStatement.xml:
    title: API


menu:
  IG Home: index.html
  Notes: notes.html
  API: CapabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Examples: examples.html
  Artifact Index: artifacts.html
  "Support\n      ":
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html

