
# ╭───────────────────────────ImplementationGuide-hl7.fhir.nz.base.json────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.nz.cca
canonical: http://clinfhir.com/fhir
version: 0.1.0
name: CcaImplementationGuide
title: HL7® FHIR® Te Aho o Te Kahu, Cancer Control Agency Implementation Guide
status: active
publisher:
  name: David Hay
  email: mailto:david.hay25@gmail.com
description: CCA IG
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
history:
  current: http://build.fhir.org/ig/example/example-ig
  0.0.1:
    fhirversion: 4.0.1
    date: 2099-01-01
    desc: Initial STU ballot (Mmm yyyy Ballot)
    path: http://example.org/fhir/STU1
    status: ballot
    sequence: STU 1
    current: true

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To control the ig.ini using this config, uncomment and set the "template" property.           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
template: fhir.base.template#current


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Notes: notes.html
  API: CapabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Examples: examples.html
#   Table of Contents: toc.html
  Artifact Index: artifacts.html
  "Support\n      ":
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html

